Repository mozilla/bugbot, pull requests merged in 2022-11, with the labels that each got.

#1726 Change the mode for `runauto_nag_weekdays.sh` to be executable
  runauto_nag_weekdays.sh
Labels: bug

#1756 [regression_set_status_flags] Don't consider `---` for latest status
  auto_nag/scripts/regression_set_status_flags.py
Labels: bug

#1754 Copy accessibility related metadata from duplicate bugs
  auto_nag/scripts/duplicate_copy_metadata.py
  auto_nag/utils.py
  runauto_nag_hourly.sh
  templates/duplicate_copy_metadata.html
Labels: to-be-announced

#1764 Don't consider P2 as high priority
  auto_nag/constants.py
Labels: area-Noise Reduction

#1770 [duplicate_copy_metadata] Filter out closed bugs locally
  auto_nag/scripts/duplicate_copy_metadata.py
Labels: enhancement

#1773 [duplicate_copy_metadata] Fix the table in the comment
  auto_nag/scripts/duplicate_copy_metadata.py
Labels: bug

#1774 [inactive_ni_pending] Reduce the threshold for recent activity to be 5 weeks
  auto_nag/scripts/inactive_ni_pending.py
Labels: area-User Inactivity, area-Noise Reduction

#1775 [inactive_ni_pending] Relax the conditions to close bugs
  auto_nag/scripts/inactive_ni_pending.py
Labels: area-User Inactivity, area-Noise Reduction

#1783 Remove unnecessary margins for lists in email tables
  templates/duplicate_copy_metadata.html
  templates/inactive_reviewer.html
  templates/ni_from_manager.html
  templates/tracked_attention.html
  templates/tracked_needinfo.html
  templates/tracked_needinfo_nag.html
  templates/tracking.html
  templates/tracking_nag.html
  templates/triage_rotations_outdated.html
Labels: enhancement

#1786 Add a tool to suggest increasing the severity of performance-impacting bugs
  auto_nag/scripts/severity_high_performance_impact.py
  templates/severity_high_performance_impact.html
  templates/severity_high_performance_impact_needinfo.txt
Labels: to-be-announced
